let userScore=0;
let computerScore=0;
       
        const choices=document.querySelectorAll(".choice");//i want to access all the choice
        const msg=document.querySelector("#msg");
        const userScorePara=document.querySelector("#user-score");
        const comScorePara=document.querySelector("#computer-score");
//create a random value from thr choice which generated by the computer
const genComChoice=()=>{
const options=["rock","paper","scissors"];
    const randomIdx=Math.floor(Math.random() * 3);
    return options[randomIdx];
};
const drawGame = () => {
    console.log("game was draw");
    msg.innerText="game was draw.play again"
    msg.style.backgroundColor="yellow";
};

const showWinnwer=(userWin)=>{
    if(userWin){
        userScore++;
        userScorePara.innerText=userScore;
        console.log("user win!");
        msg.innerText="you win!";
        msg.style.backgroundColor="green";
    }
    else{
        computerScore++;
        comScorePara.innerText=computerScore;
        console.log("you loss!");
        msg.innerText="you loss!";
        msg.style.backgroundColor="red";
       
    }
} 

const playGame=(userChoice)=>{
    console.log("userChoice=", userChoice); //generate user choice
    //generate computer choice
    const comChoice = genComChoice();
    console.log("comChoice=", comChoice); //generate computer choice
    if (userChoice === comChoice) {
        //draw game
        drawGame();
    }
    else{
        let userWin=true;
        
        if(userChoice==="rock"){
            //scissors,paper
         userWin = comChoice === "paper" ? false : true;
        }
        else if(userChoice === "paper"){
            //rock,scissors
            userWin = comChoice === "scissors" ? false : true;
        }
        else{
            //rock,paper
            userWin=comChoice==="rock"?false:true;
        }
        showWinnwer(userWin);
        }
    };  




        choices.forEach((choice)=>{//select for all choice
            console.log(choice);//print the choice
            choice.addEventListener("click",()=>{//click the choices
             const userChoice=choice.getAttribute("id");   
            console.log("choice was clicked!",userChoice);//click the choice then print the message


            playGame(userChoice);//call the user choice


        });
    });